Algoritmo "EX_lacoPara"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Algoritmo que testa a funcionalidade do laço "PARA"
// Autor(a)    : Lucas Rocha
// Data atual  : 03/09/2021
Var
// Seção de Declarações das variáveis
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para cont de 1 ate 10 passo 1 faca
escreval("Laço PARA")
fimpara

Fimalgoritmo