Algoritmo "EX_lacoRepeticao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Algoritmo que usa um laço de repetição para repetir uma
// mensagem
// Autor(a)    : Lucas Rocha
// Data atual  : 01/09/2021
Var
// Seção de Declarações das variáveis
i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
enquanto i<10 faca
Escreval("Mensagem sendo repetida")
i<-i+1
fimenquanto

Fimalgoritmo