Algoritmo "Exibir mensagem"
// Disciplina   : [Lógica de programação e algoritmos]
// Professor   : Jailson
// Descrição   : Exibir mensagem
// Autor(a)    : Lucas Rocha
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Jailson - Osasco")
escreval("Lucas - SP")
escreval("Equipe 04")


Fimalgoritmo